### ISSUE TITLE
Could not execute `tfschema resource list aws` 

### ISSUE THREAD

**Issue by ken5scal** [minamijoyo/tfschema#1]
Hi, I just installed tfschema with brew, but failed to execute first tfschema command in Mac Sierra.

```
% uname -a
Darwin A-M-201711-003 16.7.0 Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64
```

When I try to execute `tfschema resource list aws`, it says

```
% tfschema resource list aws
Failed to find plugin: aws. Plugin binary was not found in any of the following directories: [., /Users/ksuzuki/usr/local/bin, terraform.d/plugins/darwin_amd64, .terraform/plugins/darwin_amd64, /Users/ksuzuki/.terraform.d/plugins, /Users/ksuzuki/.terraform.d/plugins/darwin_amd64, /Users/ksuzuki/workspace/go/bin]
```

However, my aws command already exists under valid directory.
```
% which aws
/Users/ksuzuki/usr/local/bin/aws
```

**Comment by minamijoyo** [comment]
@ken5scal Thank you for opening the issue. The tfschema uses a terraform provider binary for aws not aws-cli, so you need to install `terraform-provider-aws`. You can install it with `terraform init` command.  The tfschema can use the same provider's binary as terraform uses, so you can run `tfschema` command in the same directory where you run the terraform command.
See also: https://github.com/minamijoyo/tfschema/blob/0980d8e264ae59d76e65cafec7188c68a440a62e/README.md#rules-of-finding-providers-binary

**Comment by ken5scal** [comment]
oh, makes sense! It works now, much appreciated.
