### ISSUE TITLE
'tfschema resource browse <resource>' is generating broken links

### ISSUE THREAD

**Issue by b-rad36** [minamijoyo/tfschema#37]
### Issue
Using `tfschema resource browse <resource>` (or `tfschema data browse <data>`) opens a non-functioning link.

### Version
```
$ tfschema --version
0.7.1
```
### Examples
- AWS: Security Group
  - `tfschema resource browse aws_security_group`: [https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group.html](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group.html)
  - ![Screen Shot 2021-12-17 at 4 30 38 PM](https://user-images.githubusercontent.com/56605963/146619499-dc51d0b6-7930-4697-9e4b-d2aecd10be22.png)
- Azure: CDN Endpoint
  - `tfschema resource browse azurerm_cdn_endpoint`: [https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_endpoint.html](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_endpoint.html)
  - ![Screen Shot 2021-12-17 at 4 31 00 PM](https://user-images.githubusercontent.com/56605963/146620346-64fd80df-d11d-4735-b673-e002f0be5d91.png)
- GCP: App Engine Application
  - `tfschema resource browse google_app_engine_application`: [https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/app_engine_application.html](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/app_engine_application.html)
  - ![Screen Shot 2021-12-17 at 4 31 05 PM](https://user-images.githubusercontent.com/56605963/146620347-7eea6279-d635-4474-a684-ecc6813a3fd8.png)
- Kubernetes: Deployment
  -  `tfschema resource browse kubernetes_deployment`: [https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/deployment.html](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/deployment.html)
  - ![Screen Shot 2021-12-17 at 4 30 54 PM](https://user-images.githubusercontent.com/56605963/146620344-02e4374f-8c27-4b89-9a6b-c46c376fff87.png)
- Okta: Group
  -  `tfschema resource browse okta_group`: [https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/group.html](https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/group.html)
  - ![Screen Shot 2021-12-17 at 4 30 46 PM](https://user-images.githubusercontent.com/56605963/146620343-b4a43e5c-306c-486f-a472-5b1c784f02b2.png)

### Resolution
In each case, removing `.html` from the end of the URL will direct to the correct page:
- AWS: Security Group
  - ![Screen Shot 2021-12-17 at 4 31 40 PM](https://user-images.githubusercontent.com/56605963/146619511-f1f821cd-d82c-4831-9216-9177db3f3af1.png)
- Azure: CDN Endpoint
  - ![Screen Shot 2021-12-17 at 4 54 37 PM](https://user-images.githubusercontent.com/56605963/146620562-fe334b03-1f3c-467d-8d63-0d7363826d8d.png)
- GCP: App Engine Application
  - ![Screen Shot 2021-12-17 at 4 54 48 PM](https://user-images.githubusercontent.com/56605963/146620563-fe5f0f67-e1d7-4b6e-87c0-b618c1038360.png)
- Kubernetes: Deployment
  - ![Screen Shot 2021-12-17 at 4 54 30 PM](https://user-images.githubusercontent.com/56605963/146620561-b88edd66-da28-4069-ad9a-bfd014022270.png)
- Okta: Group
  - ![Screen Shot 2021-12-17 at 4 54 23 PM](https://user-images.githubusercontent.com/56605963/146620560-14cd0049-c172-47c1-98f9-4aee379e351e.png)

**Comment by minamijoyo** [comment]
Fixed v0.7.2 via #38
