### ISSUE TITLE
Dynamic library issues

### ISSUE THREAD

**Issue by Nuru** [minamijoyo/tfschema#53]
The v0.7.6 release does not work on Apline or Ubutnu (or probably Debian, either) due to dynamic linking issues. This is a known consequence of upgrading from Go 1.19 to 1.20 or later. You need to explicitly set `CGO_ENABLED=0` in your build.

See https://github.com/golang/go/issues/58550 for some details.

**Comment by minamijoyo** [comment]
Hi @Nuru, Thank you for reporting this! Fixed in v0.7.7.
