### ISSUE TITLE
Add RST formatter

### ISSUE THREAD

**Issue by keiichi-hikita** [minamijoyo/tfschema#7]
Hi minamijoyo,

Nice to e-meet you.
My name is Keiichi Hikita, Custom Provider Developer of our cloud service "Enterprise Cloud 2.0" .
(https://www.ntt.com/business/services/cloud/iaas/enterprise-cloud.html)

(Exactly saying, this is not a "issue" ...)

We were finding good management way of documentation of each resources, especially about Schema, then found this good and suitable tool, tfschema.
(I found it here: http://engineer.crowdworks.jp/entry/2018/03/27/173704)

But in our service, all documentations are managed as "rst(sphinx)".
So I would like to develop "rst formatter" of tfschema.

Would it be okay to propose this?
If you allow me about this, I would like to develop that and would like to send PR.
(From me, of maybe my team's other member)

Anyway, I would like to ask your impression on this point.

Thanks.

**Comment by minamijoyo** [comment]
Hi @keiichi-hikita, Thank you for your interest.

I'm not a sphinx user, so I don't have the confidence to maintain the RST formatter feature.
The tfschema has a feature to output JSON, so could you convert JSON to RST with another tool?

Thanks!

**Comment by keiichi-hikita** [comment]
Hi @minamijoyo,

Thanks for your response.

Okay, I'll create another tool to convert JSON or use your tfschema as one of my library for it.
I'll close this issue.

 Thanks again!
